/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stock_management_gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySql;

/**
 *
 * @author Avishka
 */
public class BrandRegister extends javax.swing.JFrame {

    /**
     * Creates new form BrandRegister
     */
    public BrandRegister() {
        initComponents();
        addPlaceholder();
        loadBrands();
        brandNameTextField.grabFocus();
    }

    private void addPlaceholder() {

        brandNameTextField.setText("Brand Name");
        brandNameTextField.setForeground(Color.GRAY);

        companyNameTextField.setText("Company Name");
        companyNameTextField.setForeground(Color.GRAY);
    }

    private void loadBrands() {
        try {

            ResultSet resultSet = MySql.executeSearch("SELECT * FROM `brands` ");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {

                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("brands_id"));
                vector.add(resultSet.getString("brand_name"));
                vector.add(resultSet.getString("company_name"));

                model.addRow(vector);

            }
        } catch (Exception e) {

            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        brandRegistrationLable = new javax.swing.JLabel();
        brandRegisterPanel = new javax.swing.JPanel();
        brandAddSection = new javax.swing.JPanel();
        brandName = new javax.swing.JLabel();
        companyName = new javax.swing.JLabel();
        brandNameTextField = new javax.swing.JTextField();
        companyNameTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        brandTableSection = new javax.swing.JPanel();
        BackToDashboardPanel = new javax.swing.JPanel();
        BackToDashboardButton = new javax.swing.JButton();
        brandTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(153, 153, 153));
        headerPanel.setPreferredSize(new java.awt.Dimension(720, 60));

        brandRegistrationLable.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        brandRegistrationLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandRegistrationLable.setText("Brand Registration");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brandRegistrationLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brandRegistrationLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        brandRegisterPanel.setLayout(new java.awt.BorderLayout());

        brandAddSection.setPreferredSize(new java.awt.Dimension(100, 120));

        brandName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        brandName.setText("Brand Name");

        companyName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        companyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        companyName.setText("Company Name");

        brandNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                brandNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                brandNameTextFieldFocusLost(evt);
            }
        });
        brandNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                brandNameTextFieldKeyPressed(evt);
            }
        });

        companyNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameTextFieldFocusLost(evt);
            }
        });
        companyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameTextFieldActionPerformed(evt);
            }
        });
        companyNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                companyNameTextFieldKeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kButton1.setText("Add");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton1.setkPressedColor(new java.awt.Color(0, 102, 153));
        kButton1.setkSelectedColor(new java.awt.Color(0, 102, 153));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Update");
        kButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton2.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton2.setkPressedColor(new java.awt.Color(0, 102, 153));
        kButton2.setkSelectedColor(new java.awt.Color(0, 102, 153));
        kButton2.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout brandAddSectionLayout = new javax.swing.GroupLayout(brandAddSection);
        brandAddSection.setLayout(brandAddSectionLayout);
        brandAddSectionLayout.setHorizontalGroup(
            brandAddSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandAddSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brandName)
                .addGap(12, 12, 12)
                .addComponent(brandNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandAddSectionLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        brandAddSectionLayout.setVerticalGroup(
            brandAddSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandAddSectionLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(brandAddSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(brandAddSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brandName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brandNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(brandAddSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        brandRegisterPanel.add(brandAddSection, java.awt.BorderLayout.PAGE_START);

        brandTableSection.setLayout(new java.awt.BorderLayout());

        BackToDashboardPanel.setBackground(new java.awt.Color(153, 153, 153));
        BackToDashboardPanel.setPreferredSize(new java.awt.Dimension(100, 50));

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackToDashboardPanelLayout = new javax.swing.GroupLayout(BackToDashboardPanel);
        BackToDashboardPanel.setLayout(BackToDashboardPanelLayout);
        BackToDashboardPanelLayout.setHorizontalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(1027, Short.MAX_VALUE))
        );
        BackToDashboardPanelLayout.setVerticalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToDashboardButton)
                .addContainerGap())
        );

        brandTableSection.add(BackToDashboardPanel, java.awt.BorderLayout.PAGE_END);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Brand ID", "Brand Name", "Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout brandTablePanelLayout = new javax.swing.GroupLayout(brandTablePanel);
        brandTablePanel.setLayout(brandTablePanelLayout);
        brandTablePanelLayout.setHorizontalGroup(
            brandTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandTablePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        brandTablePanelLayout.setVerticalGroup(
            brandTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandTablePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        brandTableSection.add(brandTablePanel, java.awt.BorderLayout.CENTER);

        brandRegisterPanel.add(brandTableSection, java.awt.BorderLayout.CENTER);

        getContentPane().add(brandRegisterPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void companyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameTextFieldActionPerformed

    //refresh button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void brandNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandNameTextFieldFocusGained

        if (brandNameTextField.getText().equals("Brand Name")) {
            brandNameTextField.setText("");
            brandNameTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_brandNameTextFieldFocusGained

    private void brandNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brandNameTextFieldFocusLost
        if (brandNameTextField.getText().isEmpty()) {
            brandNameTextField.setText("Brand Name");
            brandNameTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_brandNameTextFieldFocusLost

    private void companyNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameTextFieldFocusGained

        if (companyNameTextField.getText().equals("Company Name")) {
            companyNameTextField.setText("");
            companyNameTextField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_companyNameTextFieldFocusGained

    private void companyNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameTextFieldFocusLost
        if (companyNameTextField.getText().isEmpty()) {
            companyNameTextField.setText("Company Name");
            companyNameTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_companyNameTextFieldFocusLost

    private void brandNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandNameTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            companyNameTextField.grabFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            
            companyNameTextField.grabFocus();
            
        }
    }//GEN-LAST:event_brandNameTextFieldKeyPressed

    private void companyNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyNameTextFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            kButton1.doClick();
        }
    }//GEN-LAST:event_companyNameTextFieldKeyPressed

    //Delete Function
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow();

        brandNameTextField.setText(String.valueOf(jTable1.getValueAt(row, 1)));

        companyNameTextField.setText(String.valueOf(jTable1.getValueAt(row, 2)));

        if (evt.getClickCount() == 2) {

            String selectedBrandID = String.valueOf(jTable1.getValueAt(row, 0));

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Brand?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                try {

                    MySql.executeUpdate("DELETE FROM `brands` WHERE `brands_id`='" + selectedBrandID + "'");

                    MySql.executeUpdate("SET @row_number = 0");
                    MySql.executeUpdate("UPDATE `brands` "
                            + "SET `brands_id` = (@row_number := @row_number + 1) "
                            + "ORDER BY `brands_id`");

                    MySql.executeUpdate("ALTER TABLE `brands` AUTO_INCREMENT = 1");

                    loadBrands();
                    
                    reset();

                    JOptionPane.showMessageDialog(this, "Brand Deleted Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {

                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error occurred while deleting the Brand", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    //Add Button
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        try {

            String brand = brandNameTextField.getText();
            String company = companyNameTextField.getText();

            if (brand.isEmpty() || brand.equals("Brand Name")) {

                JOptionPane.showMessageDialog(this, "Please enter Brand Name", "Warning", JOptionPane.WARNING_MESSAGE);

                brandNameTextField.grabFocus();
                
            } else if (company.isEmpty() || company.equals("Company Name")) {

                JOptionPane.showMessageDialog(this, "Please enter Company Name", "Warning", JOptionPane.WARNING_MESSAGE);

                companyNameTextField.grabFocus();
                
            } else {

                ResultSet resultSet = MySql.executeSearch("SELECT * FROM `brands` WHERE `brand_name`= '" + brand + "'");

                if (resultSet.next()) {
                    
                    JOptionPane.showMessageDialog(this, "This Brand is already registered", "Warning", JOptionPane.WARNING_MESSAGE);
                    
                } else {

                    MySql.executeUpdate("ALTER TABLE `brands` AUTO_INCREMENT = 1");

                    MySql.executeUpdate("INSERT INTO `brands` (`brand_name`,`company_name` ) VALUES ('" + brand + "','" + company + "')");

                    loadBrands();
                    reset();

                    brandNameTextField.grabFocus();

                    JOptionPane.showMessageDialog(this, "Brand Registered Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        } catch (Exception e) {

            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while registering the Brand", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_kButton1ActionPerformed

    //Update Button
    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        int row = jTable1.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(this, "Please Select a Row", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            String brand = brandNameTextField.getText();
            String company = companyNameTextField.getText();

            String selectedBrandID = String.valueOf(jTable1.getValueAt(row, 0));

            if (brand.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please enter Brand Name", "Warning", JOptionPane.WARNING_MESSAGE);

            } else if (company.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please enter Company Name", "Warning", JOptionPane.WARNING_MESSAGE);

            } else {

                try {
                    
                    ResultSet resultSet = MySql.executeSearch("SELECT * FROM `brands` WHERE `brand_name` = '" + brand + "'");

                    if (resultSet.next()) {

                        JOptionPane.showMessageDialog(this, "Change Brand Name to update", "Warning", JOptionPane.WARNING_MESSAGE);

                    } else {
                        MySql.executeUpdate("UPDATE `brands` SET `brand_name` = '" + brand + "' , `company_name` = '" + company + "' "
                                + "WHERE `brands_id` = '" + selectedBrandID + "'");

                        loadBrands();
                        reset();

                        JOptionPane.showMessageDialog(this, "Data Updated Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error occurred while updating the Data", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        }
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrandRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JPanel BackToDashboardPanel;
    private javax.swing.JPanel brandAddSection;
    private javax.swing.JLabel brandName;
    private javax.swing.JTextField brandNameTextField;
    private javax.swing.JPanel brandRegisterPanel;
    private javax.swing.JLabel brandRegistrationLable;
    private javax.swing.JPanel brandTablePanel;
    private javax.swing.JPanel brandTableSection;
    private javax.swing.JLabel companyName;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    // End of variables declaration//GEN-END:variables

    private void reset() {

        brandNameTextField.setText("");
        brandNameTextField.grabFocus();
        companyNameTextField.setText("");
        jTable1.clearSelection();

        addPlaceholder();
    }
}
