/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr_department_gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.MySql;

/**
 *
 * @author 2003k
 */
public class AddNewCompany extends javax.swing.JFrame {

    /**
     * Creates new form AddNewCompany
     */
    public AddNewCompany() {
        initComponents();
        RegenarateButton.grabFocus();
        CompanyIdTextfield.setEditable(false);
    }
    //load company to table

    DefaultTableModel model;
    
    private void loadCompanys() {
        try {

            ResultSet resultSet = MySql.executeSearch("SELECT * FROM `company` ORDER BY `company_id` ASC ");

             model = (DefaultTableModel) CompanyRegistrationTable.getModel();
             
            model.setRowCount(0);  // Clear any existing rows in the table 

            // Loop through the result set to extract company data
            while (resultSet.next()) {

                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("company_id"));
                vector.add(resultSet.getString("company_name"));
                vector.add(resultSet.getString("company_address"));
                vector.add(resultSet.getString("company_email"));
                vector.add(resultSet.getString("hotline_number"));

                model.addRow(vector); // Add the vector as a new row to the table model

            }
        } catch (Exception e) {

            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        companyRegisterPanel = new javax.swing.JPanel();
        CompanyEmailTextfield = new javax.swing.JTextField();
        RegenarateButton = new javax.swing.JButton();
        CompanyNameTextfield = new javax.swing.JTextField();
        CompanyIdTextfield = new javax.swing.JTextField();
        CompanyHotlineNumberTextfield = new javax.swing.JTextField();
        CompanyAddressTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonTableViewPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        addButton = new com.k33ptoo.components.KButton();
        deleteButton = new com.k33ptoo.components.KButton();
        updateButton = new com.k33ptoo.components.KButton();
        RefreshButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        SearchCompanyNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CompanyRegistrationTable = new javax.swing.JTable();
        BackToDashboardPanel = new javax.swing.JPanel();
        BackToDashboardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        headerPanal.setBackground(new java.awt.Color(153, 153, 153));
        headerPanal.setPreferredSize(new java.awt.Dimension(936, 45));
        headerPanal.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Company Registration");
        jLabel1.setPreferredSize(new java.awt.Dimension(298, 50));
        headerPanal.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanal, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setLayout(new java.awt.BorderLayout());

        companyRegisterPanel.setPreferredSize(new java.awt.Dimension(936, 190));

        CompanyEmailTextfield.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CompanyEmailTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyEmailTextfield.setPreferredSize(new java.awt.Dimension(106, 32));
        CompanyEmailTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyEmailTextfieldActionPerformed(evt);
            }
        });
        CompanyEmailTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyEmailTextfieldKeyPressed(evt);
            }
        });

        RegenarateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate.png"))); // NOI18N
        RegenarateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegenarateButtonActionPerformed(evt);
            }
        });
        RegenarateButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegenarateButtonKeyPressed(evt);
            }
        });

        CompanyNameTextfield.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CompanyNameTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextfieldActionPerformed(evt);
            }
        });
        CompanyNameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyNameTextfieldKeyPressed(evt);
            }
        });

        CompanyIdTextfield.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CompanyIdTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyIdTextfield.setPreferredSize(new java.awt.Dimension(106, 32));
        CompanyIdTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyIdTextfieldKeyPressed(evt);
            }
        });

        CompanyHotlineNumberTextfield.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CompanyHotlineNumberTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyHotlineNumberTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyHotlineNumberTextfieldKeyPressed(evt);
            }
        });

        CompanyAddressTextfield.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CompanyAddressTextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyAddressTextfield.setPreferredSize(new java.awt.Dimension(106, 32));
        CompanyAddressTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyAddressTextfieldActionPerformed(evt);
            }
        });
        CompanyAddressTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyAddressTextfieldKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Company Address");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Company Email");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setText("Company ID");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setText("Company Name");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("Company Hotline");

        javax.swing.GroupLayout companyRegisterPanelLayout = new javax.swing.GroupLayout(companyRegisterPanel);
        companyRegisterPanel.setLayout(companyRegisterPanelLayout);
        companyRegisterPanelLayout.setHorizontalGroup(
            companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyRegisterPanelLayout.createSequentialGroup()
                        .addComponent(CompanyIdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegenarateButton))
                    .addComponent(CompanyAddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompanyEmailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CompanyNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(CompanyHotlineNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        companyRegisterPanelLayout.setVerticalGroup(
            companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CompanyIdTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(RegenarateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyRegisterPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompanyNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CompanyHotlineNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyRegisterPanelLayout.createSequentialGroup()
                        .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompanyAddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25)
                .addGroup(companyRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyEmailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        bodyPanel.add(companyRegisterPanel, java.awt.BorderLayout.PAGE_START);

        addButton.setText("Add");
        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setkEndColor(new java.awt.Color(0, 204, 204));
        addButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        addButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        addButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        addButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        addButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        addButton.setkStartColor(new java.awt.Color(0, 102, 153));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteButton.setkEndColor(new java.awt.Color(0, 204, 204));
        deleteButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        deleteButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deleteButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        deleteButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        deleteButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        deleteButton.setkStartColor(new java.awt.Color(0, 102, 153));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateButton.setkEndColor(new java.awt.Color(0, 204, 204));
        updateButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        updateButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        updateButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        updateButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        updateButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        updateButton.setkStartColor(new java.awt.Color(0, 102, 153));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        RefreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate.png"))); // NOI18N
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(RefreshButton)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Company Name");

        SearchCompanyNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchCompanyNameTextFieldKeyTyped(evt);
            }
        });

        CompanyRegistrationTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CompanyRegistrationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Company Name", "Company Address", "Email", "Hotline Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CompanyRegistrationTable.getTableHeader().setReorderingAllowed(false);
        CompanyRegistrationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyRegistrationTableMouseClicked(evt);
            }
        });
        CompanyRegistrationTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyRegistrationTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(CompanyRegistrationTable);

        BackToDashboardPanel.setBackground(new java.awt.Color(153, 153, 153));
        BackToDashboardPanel.setPreferredSize(new java.awt.Dimension(1025, 50));

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackToDashboardPanelLayout = new javax.swing.GroupLayout(BackToDashboardPanel);
        BackToDashboardPanel.setLayout(BackToDashboardPanelLayout);
        BackToDashboardPanelLayout.setHorizontalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackToDashboardPanelLayout.setVerticalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToDashboardButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(BackToDashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(SearchCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(53, 53, 53))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BackToDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout buttonTableViewPanelLayout = new javax.swing.GroupLayout(buttonTableViewPanel);
        buttonTableViewPanel.setLayout(buttonTableViewPanelLayout);
        buttonTableViewPanelLayout.setHorizontalGroup(
            buttonTableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonTableViewPanelLayout.setVerticalGroup(
            buttonTableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonTableViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.add(buttonTableViewPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CompanyNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextfieldActionPerformed

    private void CompanyEmailTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyEmailTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyEmailTextfieldActionPerformed

    private void CompanyAddressTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyAddressTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyAddressTextfieldActionPerformed

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed

        this.dispose();

    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        try {
            
            String companyID = CompanyIdTextfield.getText();
            
            String companyName = CompanyNameTextfield.getText();
            
            String companyAddress = CompanyAddressTextfield.getText();
            
            String companyEmail = CompanyEmailTextfield.getText();
            
            String companyHotline = CompanyHotlineNumberTextfield.getText();

            if (companyID.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Insert Company ID", "Empty", JOptionPane.WARNING_MESSAGE);
                RegenarateButton.grabFocus();

            } else if (companyName.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Entre Company Name", "Empty", JOptionPane.WARNING_MESSAGE);
                CompanyNameTextfield.grabFocus();

            } else if (companyAddress.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Entre Company Address", "Empty", JOptionPane.WARNING_MESSAGE);
                CompanyAddressTextfield.grabFocus();

            } else if (companyEmail.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Entre Company Email", "Empty", JOptionPane.WARNING_MESSAGE);
                CompanyEmailTextfield.grabFocus();

            } else if (!companyEmail.matches("^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {

                JOptionPane.showMessageDialog(this, "Please Entre a valid Email", "Empty", JOptionPane.WARNING_MESSAGE);
                CompanyEmailTextfield.grabFocus();

            } else if (companyHotline.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Enter mobile number", "Warning", JOptionPane.WARNING_MESSAGE);
                CompanyHotlineNumberTextfield.grabFocus();

            } else if (!companyHotline.matches("^(?:0|94|\\+94|0094)?(?:(11|21|23|24|25|26|27|31|32|33|34|35|36|37|38|41|45|47|51|52|54|55|57|63|65|66|67|81|91)(0|2|3|4|5|7|9)|7(0|1|2|4|5|6|7|8)\\d)\\d{6}$")) {

                JOptionPane.showMessageDialog(this, "Please enter valid mobile number", "Warning", JOptionPane.WARNING_MESSAGE);
                CompanyHotlineNumberTextfield.grabFocus();

            } else if (companyHotline.length() != 10) {

                JOptionPane.showMessageDialog(this, "Mobile number must be included 10 characters only", "Warning", JOptionPane.WARNING_MESSAGE);
                CompanyHotlineNumberTextfield.grabFocus();

            } else {

                ResultSet resultset = MySql.executeSearch("SELECT * FROM `company` WHERE `company_id` = '" + companyID
                        + "' OR `hotline_number` = '" + companyHotline + "'");

                if (resultset.next()) {

                    JOptionPane.showMessageDialog(this, "Company Already Registered", "Error", JOptionPane.ERROR_MESSAGE);
                    RegenarateButton.grabFocus();

                } else {

                    MySql.executeUpdate("INSERT INTO `company` (`company_id`,`company_name`,`company_address`,`company_email`,`hotline_number`)"
                            + " VALUES ('" + companyID + "','" + companyName + "','" + companyAddress + "','" + companyEmail + "',"
                            + " '" + companyHotline + "')");

                    reset();

                    loadCompanys();

                    JOptionPane.showMessageDialog(this, companyName+" "+"company registerd successfully", "Company Registration Success", JOptionPane.INFORMATION_MESSAGE);

                }

            }

        } catch (Exception e) {

            e.printStackTrace();

        }


    }//GEN-LAST:event_addButtonActionPerformed

    private void RegenarateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegenarateButtonActionPerformed
        // Sets Hand Icon to select Employee ID
        CompanyIdTextfield.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Sets back to Employee Id Color origin
        CompanyIdTextfield.setForeground(Color.BLACK);

        // Generate Id when button clicked
        long id = System.currentTimeMillis();
        CompanyIdTextfield.setText("ECR" + String.valueOf(id));

        // Request focus to the text field
        CompanyIdTextfield.setFocusable(true);

    }//GEN-LAST:event_RegenarateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Get the index of the selected row in the jtable
        int selectedRow = CompanyRegistrationTable.getSelectedRow(); //Row selected

        //Check if no row selected
        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(this, "Please Select a Row to delete Company ", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                // Get the company ID of the selected row
                String selectedCompanyId = String.valueOf(CompanyRegistrationTable.getValueAt(selectedRow, 0));

                // Confirm before the deletion
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this company?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {

                    // Delete the selected company from the database
                    MySql.executeUpdate("DELETE FROM `company` WHERE `company_id`='" + selectedCompanyId + "' ");

                    //load to table
                    reset();

                    loadCompanys();
                    //success message
                    JOptionPane.showMessageDialog(this, "Company Deleted Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

                }

            } catch (Exception e) {

                e.printStackTrace();
                // Show an error message if the operation fails
                JOptionPane.showMessageDialog(this, "Error occurred while deleting the Compnay.", "Error", JOptionPane.ERROR_MESSAGE);

            }

        }


    }//GEN-LAST:event_deleteButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadCompanys();
    }//GEN-LAST:event_formWindowOpened

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        reset();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Get the index of the selected row in the table
        int row = CompanyRegistrationTable.getSelectedRow(); //Row selected

        //Check if no row selected
        if (row == -1) {

            // Show a warning message if no row is selected
            JOptionPane.showMessageDialog(this, "Please Select a Row", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            String companyID = CompanyIdTextfield.getText();
            
            String companyName = CompanyNameTextfield.getText();

            String selectedCompanyID = String.valueOf(CompanyRegistrationTable.getValueAt(row, 0));

            String selectedCompanyName = String.valueOf(CompanyRegistrationTable.getValueAt(row, 1));

            String selectedCompanyAddress = String.valueOf(CompanyRegistrationTable.getValueAt(row, 2));

            String selectedCompanyEmail = String.valueOf(CompanyRegistrationTable.getValueAt(row, 3));

            String selectedCompanyHotline = String.valueOf(CompanyRegistrationTable.getValueAt(row, 4));
            
            boolean companyUpdate = false;

            try {

                //Search from Database
                ResultSet resultSet = MySql.executeSearch("SELECT * FROM `company` WHERE (`company_name`='" + companyName + "') AND `company_id` != '" + selectedCompanyID + "'");

                if (resultSet.next()) {

                    if (!resultSet.getString("company_id").equals(companyID)) {

                        JOptionPane.showMessageDialog(this, "This Company name is already used", "Warning", JOptionPane.WARNING_MESSAGE);

                    } else {

                        companyUpdate = true;

                    }

                } else {

                    companyUpdate = true;

                    if (companyUpdate) {

                        //Update the Database
                        MySql.executeUpdate("UPDATE `company` SET `company_name` = '" + selectedCompanyName + "', `company_address` = '" + selectedCompanyAddress + "', `company_email` = '" + selectedCompanyEmail + "', `hotline_number` = '" + selectedCompanyHotline + "' WHERE `company_id` = '" + selectedCompanyID + "' ");

                        //load to table
                        reset();

                        loadCompanys();

                        //success message
                        JOptionPane.showMessageDialog(this, selectedCompanyName+" "+"company updated successfully", "Company Update Successfully", JOptionPane.INFORMATION_MESSAGE);

                    }

                }

            } catch (Exception e) {

                e.printStackTrace();
                // Show an error message if the operation fails
                JOptionPane.showMessageDialog(this, "Error occurred while updating the Company", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void CompanyRegistrationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyRegistrationTableMouseClicked

        int row = CompanyRegistrationTable.getSelectedRow();

        RegenarateButton.setEnabled(rootPaneCheckingEnabled);

        CompanyIdTextfield.setText(String.valueOf(CompanyRegistrationTable.getValueAt(row, 0)));
        
        
        CompanyNameTextfield.setText(String.valueOf(CompanyRegistrationTable.getValueAt(row, 1)));
        CompanyNameTextfield.setEditable(false);
        
        CompanyAddressTextfield.setText(String.valueOf(CompanyRegistrationTable.getValueAt(row, 2)));
        CompanyAddressTextfield.setEditable(false);
        
        CompanyEmailTextfield.setText(String.valueOf(CompanyRegistrationTable.getValueAt(row, 3)));
        CompanyEmailTextfield.setEditable(false);
        
        CompanyHotlineNumberTextfield.setText(String.valueOf(CompanyRegistrationTable.getValueAt(row, 4)));        
        CompanyHotlineNumberTextfield.setEditable(false);
        
    }//GEN-LAST:event_CompanyRegistrationTableMouseClicked

    private void CompanyIdTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyIdTextfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            CompanyNameTextfield.grabFocus();

        }

    }//GEN-LAST:event_CompanyIdTextfieldKeyPressed

    private void CompanyNameTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyNameTextfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            CompanyAddressTextfield.grabFocus();

        }

    }//GEN-LAST:event_CompanyNameTextfieldKeyPressed

    private void CompanyAddressTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyAddressTextfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            CompanyEmailTextfield.grabFocus();

        }

    }//GEN-LAST:event_CompanyAddressTextfieldKeyPressed

    private void CompanyEmailTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyEmailTextfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            CompanyHotlineNumberTextfield.grabFocus();

        }

    }//GEN-LAST:event_CompanyEmailTextfieldKeyPressed

    private void CompanyHotlineNumberTextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyHotlineNumberTextfieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            addButton.doClick();

        }

    }//GEN-LAST:event_CompanyHotlineNumberTextfieldKeyPressed

    private void RegenarateButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegenarateButtonKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            CompanyIdTextfield.grabFocus();

        }

    }//GEN-LAST:event_RegenarateButtonKeyPressed

    private void CompanyRegistrationTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyRegistrationTableKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            updateButton.doClick();
            
        }
        
    }//GEN-LAST:event_CompanyRegistrationTableKeyPressed

    private void SearchCompanyNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchCompanyNameTextFieldKeyTyped
        
        String companyNameSearch = SearchCompanyNameTextField.getText();
        
        searchName(companyNameSearch);
        
    }//GEN-LAST:event_SearchCompanyNameTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JPanel BackToDashboardPanel;
    private javax.swing.JTextField CompanyAddressTextfield;
    private javax.swing.JTextField CompanyEmailTextfield;
    private javax.swing.JTextField CompanyHotlineNumberTextfield;
    private javax.swing.JTextField CompanyIdTextfield;
    private javax.swing.JTextField CompanyNameTextfield;
    private javax.swing.JTable CompanyRegistrationTable;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton RegenarateButton;
    private javax.swing.JTextField SearchCompanyNameTextField;
    private com.k33ptoo.components.KButton addButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonTableViewPanel;
    private javax.swing.JPanel companyRegisterPanel;
    private com.k33ptoo.components.KButton deleteButton;
    private javax.swing.JPanel headerPanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel tablePanel;
    private com.k33ptoo.components.KButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        CompanyIdTextfield.setText("");
        RegenarateButton.setEnabled(true);
        CompanyNameTextfield.setEnabled(true);
        CompanyRegistrationTable.clearSelection();
        CompanyAddressTextfield.setEditable(true);
        CompanyEmailTextfield.setEnabled(true);
        CompanyHotlineNumberTextfield.setEditable(true);
        CompanyRegistrationTable.clearSelection();
        RegenarateButton.grabFocus();
        CompanyNameTextfield.setText("");
        CompanyAddressTextfield.setText("");
        CompanyHotlineNumberTextfield.setText("");
        CompanyEmailTextfield.setText("");
    }

    private void searchName(String companyNameSearch) {
        
        model = (DefaultTableModel)CompanyRegistrationTable.getModel();
        
        TableRowSorter<DefaultTableModel> ctrs = new TableRowSorter<>(model);
        
        CompanyRegistrationTable.setRowSorter(ctrs);
        
        if (companyNameSearch.trim().length() == 0) {
            
            ctrs.setRowFilter(null);
            
        }else{
            
            ctrs.setRowFilter(RowFilter.regexFilter("(?i)" + companyNameSearch, 1));
            
        }
        
    }

}
