/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr_department_gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.TimerTask;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTD;
import model.MySql;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sanja
 */
public class MarkAttendance extends javax.swing.JFrame {

    /**
     * Creates new form Mark_Attendance
     */
    public MarkAttendance() {

        initComponents();
        loadAttendanceTable();
        dateLoad();
        timeLoade();
        scheduleDailyReset();
        
        emp_id_name_fields.addActionListener(e -> loadAttendanceDetailsByDateRange());  // Handles Enter key press For Empname Serarch Fields
        
    }

    public void dateLoad() {

        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy - MM - dd");
        String dateformat = dateFormat.format(date);
        DateLabel.setText(dateformat);

    }

//    Timer t;
    SimpleDateFormat format;

    public void timeLoade() {

        Timer t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Date dt = new Date();
                format = new SimpleDateFormat("hh : mm : ss");

                String ti = format.format(dt);
                TimeLabel.setText(ti);

            }
        });

        t.start();

    }

    DefaultTableModel model;

    // Load the attendance table data into JTable
    private void loadAttendanceTable() {

        try {

            // Clear the existing table data
            DefaultTableModel model = (DefaultTableModel) AttendanceTable.getModel();
            model.setRowCount(0);

            // Fetch the data from the database
            String query = "SELECT * FROM `temp_employee_attendance`";
            ResultSet rs = MySql.executeSearch(query);

            // Iterate through the ResultSet
            while (rs.next()) {

                // Fetch employee details from the ResultSet
                int attendanceId = rs.getInt("attendance_id");
                String EmpID = rs.getString("employee_employee_id");
                String fullName = rs.getString("employee_name");
                String date = rs.getString("date");
                String time = rs.getString("time");
                String status = rs.getString("attendence_type_type_id").equals("1") ? "Present" : "Absent";

                // Add a new row with EmpID, fullName, current date, and a placeholder for current time
                model.addRow(new Object[]{attendanceId, EmpID, fullName, date, time, status});

            }

        } catch (Exception e) {

            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        BackToDashboardButton = new javax.swing.JButton();
        PrintButtton = new com.k33ptoo.components.KButton();
        bodyPanel = new javax.swing.JPanel();
        attendanceMarkPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        employeeIDTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        employeeNameTextField = new javax.swing.JTextField();
        addButton = new com.k33ptoo.components.KButton();
        refreshButton = new javax.swing.JButton();
        sortPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        emp_id_name_fields = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AttendanceTable = new javax.swing.JTable();
        SearchButton = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        headPanel.setBackground(new java.awt.Color(153, 153, 153));
        headPanel.setPreferredSize(new java.awt.Dimension(944, 50));

        jLabel1.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        jLabel1.setText("Attendance");

        DateLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel.setText("DD / MM / YYYY");

        TimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLabel.setText("HH :: MM :: SS");

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headPanelLayout.createSequentialGroup()
                        .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(headPanel, java.awt.BorderLayout.PAGE_START);

        footerPanel.setBackground(new java.awt.Color(153, 153, 153));
        footerPanel.setPreferredSize(new java.awt.Dimension(944, 50));

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        PrintButtton.setText("Print Report");
        PrintButtton.setToolTipText("Click Here to Delete Current Selected Employee Data Row!");
        PrintButtton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PrintButtton.setkEndColor(new java.awt.Color(0, 204, 204));
        PrintButtton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        PrintButtton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        PrintButtton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        PrintButtton.setkPressedColor(new java.awt.Color(0, 102, 153));
        PrintButtton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        PrintButtton.setkStartColor(new java.awt.Color(0, 102, 153));
        PrintButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButttonActionPerformed(evt);
            }
        });
        PrintButtton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrintButttonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BackToDashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 724, Short.MAX_VALUE)
                .addComponent(PrintButtton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrintButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToDashboardButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

        bodyPanel.setLayout(new java.awt.BorderLayout());

        attendanceMarkPanel.setPreferredSize(new java.awt.Dimension(984, 100));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Employee ID");

        employeeIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIDTextFieldActionPerformed(evt);
            }
        });
        employeeIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeIDTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeIDTextFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setText("Employee Name");

        employeeNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeNameTextFieldKeyReleased(evt);
            }
        });

        addButton.setText("Add");
        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setkEndColor(new java.awt.Color(0, 204, 204));
        addButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        addButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        addButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        addButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        addButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        addButton.setkStartColor(new java.awt.Color(0, 102, 153));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attendanceMarkPanelLayout = new javax.swing.GroupLayout(attendanceMarkPanel);
        attendanceMarkPanel.setLayout(attendanceMarkPanelLayout);
        attendanceMarkPanelLayout.setHorizontalGroup(
            attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceMarkPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(attendanceMarkPanelLayout.createSequentialGroup()
                        .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(refreshButton)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        attendanceMarkPanelLayout.setVerticalGroup(
            attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendanceMarkPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, attendanceMarkPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(attendanceMarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bodyPanel.add(attendanceMarkPanel, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setText("Employee ID / Name");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setText("To");

        AttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attendance_ID", "Employee_ID", "Employee_Name", "Date", "Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AttendanceTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(AttendanceTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        SearchButton.setText("Search");
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchButton.setkEndColor(new java.awt.Color(0, 204, 204));
        SearchButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        SearchButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        SearchButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        SearchButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        SearchButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        SearchButton.setkStartColor(new java.awt.Color(0, 102, 153));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortPanelLayout = new javax.swing.GroupLayout(sortPanel);
        sortPanel.setLayout(sortPanelLayout);
        sortPanelLayout.setHorizontalGroup(
            sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sortPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sortPanelLayout.createSequentialGroup()
                        .addComponent(emp_id_name_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        sortPanelLayout.setVerticalGroup(
            sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sortPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emp_id_name_fields)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.add(sortPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed

        dispose();

    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void employeeIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIDTextFieldActionPerformed

    private void employeeIDTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIDTextFieldKeyReleased

        String EmplyeeId = employeeIDTextField.getText();

        try {

            if (EmplyeeId.isEmpty()) {

                employeeNameTextField.setText("");
                employeeIDTextField.setEditable(true);
                employeeNameTextField.setEditable(false);
                return;

            }

            ResultSet rs = MySql.executeSearch("SELECT * FROM `employee` WHERE `employee_id` = '" + EmplyeeId + "' ");

            if (rs.next()) {

                String fname = rs.getString("first_name");
                String lname = rs.getString("last_name");
                String fullname = fname + " " + lname;

                employeeNameTextField.setText(fullname);

            } else {

                employeeNameTextField.setText("");
                employeeNameTextField.setEditable(false);

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }//GEN-LAST:event_employeeIDTextFieldKeyReleased

    private void employeeNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNameTextFieldKeyReleased

        String EmpName = employeeNameTextField.getText();

        try {
            if (EmpName.isEmpty()) {

                employeeIDTextField.setText("");
                employeeNameTextField.setEditable(true);
                employeeIDTextField.setEditable(false);
                return;

            }

            // SQL query updated to handle both first name and last name correctly
            ResultSet rs = MySql.executeSearch(
                    "SELECT `employee_id` FROM `employee` WHERE "
                    + "`first_name` = '" + EmpName + "' OR "
                    + "`last_name` = '" + EmpName + "' OR "
                    + "CONCAT(`first_name`, ' ', `last_name`) = '" + EmpName + "'"
            );

            if (rs.next()) {

                String employeeId = rs.getString("employee_id");
                employeeIDTextField.setText(employeeId);

            } else {

                employeeIDTextField.setText("");
                employeeIDTextField.setEditable(false);

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }//GEN-LAST:event_employeeNameTextFieldKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        // Get the values from the text fields
        String employeeId = employeeIDTextField.getText().trim();
        String employeeName = employeeNameTextField.getText().trim();

        // Validate the inputs
        if (employeeId.isEmpty() || employeeName.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please enter both Employee ID and Employee Name.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;

        }

        // Call the method to add the attendance
        addAttendance(employeeId, employeeName);

        // Refresh the JTable view
        loadAttendanceTable();

        reset();

    }//GEN-LAST:event_addButtonActionPerformed

    private void addAttendance(String employeeId, String employeeName) {

        try {

            // Get current date and time
            Date now = new Date();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

            String currentDate = dateFormat.format(now);

            String currentTime = timeFormat.format(now);

            // Check if attendance already exists for the same employee and date in temp_employee_attendance table
            String checkQuery = "SELECT * FROM `temp_employee_attendance` WHERE `employee_employee_id` = '" + employeeId + "' AND date = '" + currentDate + "'";

            ResultSet rs = MySql.executeSearch(checkQuery);

            if (rs.next()) {

                // If record exists, show a message and exit
                JOptionPane.showMessageDialog(null, "Attendance already marked for This Employee on this date.", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
                return;

            }

            // If no record exists, proceed to insert data in both tables
            // Define the attendance status
            String status = "Present";

            int attendencetype = 1;  // Presumably for "Present" status

            // Insert Data into employee_attendance table
            String insertQuery = "INSERT INTO employee_attendence (employee_employee_id, employee_name, date, time,attendence_type_type_id) "
                    + "VALUES ('" + employeeId + "','" + employeeName + "', '" + currentDate + "', '" + currentTime + "', '" + attendencetype + "')";

            MySql.executeUpdate(insertQuery);

            // Insert Data into temp_employee_attendance table
            String insertQuery2 = "INSERT INTO temp_employee_attendance (employee_employee_id, employee_name, date, time, attendence_type_type_id) "
                    + "VALUES ('" + employeeId + "','" + employeeName + "', '" + currentDate + "', '" + currentTime + "', '" + attendencetype + "')";

            int rows = MySql.executeUpdate(insertQuery2);

            // Show success or failure message
            if (rows > 0) {

                JOptionPane.showMessageDialog(null, "Attendance marked successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            } else {

                JOptionPane.showMessageDialog(null, "Failed to mark attendance.", "Error", JOptionPane.ERROR_MESSAGE);

            }

            // Refresh the JTable view
            loadAttendanceTable();

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed

        loadAttendanceDetailsByDateRange();

    }//GEN-LAST:event_SearchButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        reset();

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            // Get the values from the text fields
            String employeeId = employeeIDTextField.getText().trim();
            String employeeName = employeeNameTextField.getText().trim();

            // Validate the inputs
            if (employeeId.isEmpty() || employeeName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter Valide Employee ID and Employee Name.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Call the method to add the attendance
            addAttendance(employeeId, employeeName);

            // Refresh the JTable view
            loadAttendanceTable();

            reset();

        }

    }//GEN-LAST:event_addButtonKeyPressed

    private void employeeIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIDTextFieldKeyPressed

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {

            // Get the values from the text fields
            String employeeId = employeeIDTextField.getText().trim();
            String employeeName = employeeNameTextField.getText().trim();

            // Validate the inputs
            if (employeeId.isEmpty() || employeeName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter Valide Employee ID and Employee Name.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Call the method to add the attendance
            addAttendance(employeeId, employeeName);

            // Refresh the JTable view
            loadAttendanceTable();

            reset();

        }

    }//GEN-LAST:event_employeeIDTextFieldKeyPressed

    private void PrintButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButttonActionPerformed
      try {
            // Path to the compiled Jasper report
            String reportPath = "src/report/Mark Attendance.jasper";

            // Create parameters map (if needed)
            HashMap<String, Object> parameters = new HashMap<>();

            // Create data source from JTable model
            JRTableModelDataSource dataSource = new JRTableModelDataSource(AttendanceTable.getModel());

            // Fill the report
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportPath, parameters, dataSource);

            // Show the report in viewer
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage(), "Report Error", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_PrintButttonActionPerformed

    private void PrintButttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrintButttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButttonKeyPressed

    private static void scheduleDailyReset() {

        java.util.Timer timer = new java.util.Timer();

        TimerTask resetTask = new TimerTask() {

            @Override

            public void run() {

                try {

                    resetAttendanceTable();

                } catch (Exception e) {

                    e.printStackTrace();

                }

            }

        };

        Calendar calendar = Calendar.getInstance();

        calendar.set(Calendar.HOUR_OF_DAY, 16); // 4 PM

        calendar.set(Calendar.MINUTE, 0);

        calendar.set(Calendar.SECOND, 0);

        // If the time has already passed today, schedule for tomorrow
        if (calendar.getTime().before(new java.util.Date())) {

            calendar.add(Calendar.DAY_OF_MONTH, 1);

        }

        // Schedule the task to run daily at 9 PM
        timer.scheduleAtFixedRate(resetTask, calendar.getTime(), 24 * 60 * 60 * 1000);

    }

    private static void resetAttendanceTable() throws Exception {

        String query = "TRUNCATE TABLE temp_employee_attendance";

        MySql.executeUpdate(query);

        System.out.println("Attendance table reset successfully at 9 AM.");

    }

    private void loadAttendanceDetailsByDateRange() {
        
        try {
            // Ensure date choosers are not null
            if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please select both start and end dates.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Fetching date range from input fields
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String startDate = dateFormat.format(jDateChooser1.getDate());
            String endDate = dateFormat.format(jDateChooser2.getDate());

            // Get the employee ID or name from the input field
            String searchValue = emp_id_name_fields.getText().trim();

            // Build the base query
            String query = "SELECT * FROM `employee_attendence` "
                    + "INNER JOIN `employee` ON `employee_attendence`.`employee_employee_id` = `employee`.`employee_id` "
                    + "INNER JOIN `attendence_type` ON `employee_attendence`.`attendence_type_type_id` = `attendence_type`.`type_id` "
                    + "WHERE `employee_attendence`.`date` BETWEEN '" + startDate + "' AND '" + endDate + "'";

            // If search value is provided, extend query to filter by employee ID or name
            
            if (!searchValue.isEmpty()) {
                query += " AND (`employee_attendence`.`employee_employee_id` LIKE '" + searchValue + "' OR `employee_attendence`.`employee_name` LIKE '" + searchValue + "')";
            }

            query += " ORDER BY `employee_attendence`.`date`";

            // Execute the query and fetch results
            ResultSet resultSet = MySql.executeSearch(query);

            // Clear the table before adding new rows
            DefaultTableModel tableModel = (DefaultTableModel) AttendanceTable.getModel();
            tableModel.setRowCount(0);

            // Populate the table with fetched data
            while (resultSet.next()) {
                String attendanceId = resultSet.getString("attendance_id");
                String employeeId = resultSet.getString("employee_employee_id");
                String employeeName = resultSet.getString("employee_name");
                String date = resultSet.getString("date");
                String time = resultSet.getString("time");
                String status = resultSet.getString("attendence_type.attendence_type_name");
                
                // Add a row to the table
                tableModel.addRow(new Object[]{attendanceId, employeeId, employeeName, date, time, status});
            }

            // Notify user if no records found
            if (tableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No records found for the selected criteria.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {

            e.printStackTrace();

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendanceTable;
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JLabel DateLabel;
    private com.k33ptoo.components.KButton PrintButtton;
    private com.k33ptoo.components.KButton SearchButton;
    private javax.swing.JLabel TimeLabel;
    private com.k33ptoo.components.KButton addButton;
    private javax.swing.JPanel attendanceMarkPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JTextField emp_id_name_fields;
    private javax.swing.JTextField employeeIDTextField;
    private javax.swing.JTextField employeeNameTextField;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headPanel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel sortPanel;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    private void reset() {

        employeeIDTextField.setText("");
        emp_id_name_fields.setText("");
        loadAttendanceTable();
        employeeNameTextField.setText("");
        AttendanceTable.clearSelection();
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);

    }
}
