/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr_department_gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.MySql;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2003k
 */
public class PayrollIntegrations extends javax.swing.JFrame {

    /**
     * Creates new form PayrollIntegrations
     */
    public PayrollIntegrations() {
        initComponents();
        loadtable();
        payrollIDTextField.setEditable(false);
        generateButton.grabFocus();
    }

    private void loadtable() {

        try {
            ResultSet resultSet = MySql.executeSearch("SELECT * FROM `payroll_int_hr_details` ORDER BY DATE(`date`)");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("payroll_id"));

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = resultSet.getDate("date");
                String formattedDate = dateFormat.format(date);
                vector.add(formattedDate);
                vector.add(resultSet.getString("employee_name"));
                vector.add(resultSet.getString("paid_price"));
                vector.add(resultSet.getString("total_advanced"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            
            e.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanal = new javax.swing.JPanel();
        headingText = new javax.swing.JLabel();
        bodyPanal = new javax.swing.JPanel();
        BackToDashboardPanel = new javax.swing.JPanel();
        BackToDashboardButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        payrollIDTextField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        employeeIDTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        employeeNameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        employeeSalaryFormattedTextField = new javax.swing.JFormattedTextField();
        addButton = new com.k33ptoo.components.KButton();
        generateButton1 = new javax.swing.JButton();
        payAdvancedButton = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        headerPanal.setBackground(new java.awt.Color(153, 153, 153));
        headerPanal.setPreferredSize(new java.awt.Dimension(874, 45));
        headerPanal.setLayout(new java.awt.BorderLayout());

        headingText.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        headingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingText.setText("Add Payroll");
        headerPanal.add(headingText, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanal, java.awt.BorderLayout.PAGE_START);

        bodyPanal.setLayout(new java.awt.BorderLayout());

        BackToDashboardPanel.setBackground(new java.awt.Color(153, 153, 153));
        BackToDashboardPanel.setPreferredSize(new java.awt.Dimension(891, 50));

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackToDashboardPanelLayout = new javax.swing.GroupLayout(BackToDashboardPanel);
        BackToDashboardPanel.setLayout(BackToDashboardPanelLayout);
        BackToDashboardPanelLayout.setHorizontalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(1071, Short.MAX_VALUE))
        );
        BackToDashboardPanelLayout.setVerticalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanal.add(BackToDashboardPanel, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Payroll ID");

        payrollIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                payrollIDTextFieldKeyPressed(evt);
            }
        });

        generateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate.png"))); // NOI18N
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        generateButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                generateButtonKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");

        employeeIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeIDTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeIDTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Employee Name");

        employeeNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeNameTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(payrollIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(generateButton)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payrollIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );

        bodyPanal.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Employee Salary");

        employeeSalaryFormattedTextField.setEnabled(false);
        employeeSalaryFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeSalaryFormattedTextFieldKeyPressed(evt);
            }
        });

        addButton.setText("Add");
        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setkEndColor(new java.awt.Color(0, 204, 204));
        addButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        addButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        addButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        addButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        addButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        addButton.setkStartColor(new java.awt.Color(0, 102, 153));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        generateButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate.png"))); // NOI18N
        generateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButton1ActionPerformed(evt);
            }
        });

        payAdvancedButton.setText("Pay Advanced");
        payAdvancedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        payAdvancedButton.setkEndColor(new java.awt.Color(0, 204, 204));
        payAdvancedButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        payAdvancedButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        payAdvancedButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        payAdvancedButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        payAdvancedButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        payAdvancedButton.setkStartColor(new java.awt.Color(0, 102, 153));
        payAdvancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payAdvancedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeSalaryFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(generateButton1)
                .addGap(90, 90, 90)
                .addComponent(payAdvancedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payAdvancedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(employeeSalaryFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payroll ID", "Date", "Employee Name", "Employee Salary", "Total Advance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1)
                .addGap(59, 59, 59))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanal.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed

        this.dispose();

    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        payrollIDTextField.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Sets back to Employee Id Color origin
        payrollIDTextField.setForeground(Color.BLACK);

        // Generate Id when button clicked
        long id = System.currentTimeMillis();
        payrollIDTextField.setText("PID" + String.valueOf(id));

        // Enable the text field (if it was disabled)
        payrollIDTextField.setEnabled(true);

        // Request focus to the text field
        payrollIDTextField.setFocusable(true);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void generateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButton1ActionPerformed

        reset();

    }//GEN-LAST:event_generateButton1ActionPerformed

    private void payAdvancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payAdvancedButtonActionPerformed

        String payId = payrollIDTextField.getText();
        
        AdvancedPayrollIntergration api = new AdvancedPayrollIntergration(this, rootPaneCheckingEnabled);
        api.setPayrollId(payId);
        api.setVisible(true);

    }//GEN-LAST:event_payAdvancedButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        String payRollId = payrollIDTextField.getText();
        String employeeId = employeeIDTextField.getText();
        String employeeName = employeeNameTextField.getText();
        String employeeSalary = employeeSalaryFormattedTextField.getText();

        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String currentDate = dateFormat.format(now);

        if (payRollId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please generate Payroll ID", "Empty", JOptionPane.ERROR_MESSAGE);
        } else if (employeeId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Employee ID", "Empty", JOptionPane.ERROR_MESSAGE);
        } else if (employeeName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Employee Name", "Empty", JOptionPane.ERROR_MESSAGE);
        } else if (employeeSalary.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Employee Salary", "Empty", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                ResultSet resultSet = MySql.executeSearch("SELECT * FROM `employee` WHERE `employee_id` = '" + employeeId + "'");

                if (!resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Invalid Employee ID", "Invalid", JOptionPane.WARNING_MESSAGE);
                } else {
                    // Fetch employee_payrolls_payroll_id
                    ResultSet payrollResult = MySql.executeSearch("SELECT payroll_id FROM employee_payrolls WHERE employee_employee_id = '" + employeeId + "'");
                    String payrollsPayrollId = null;
                    if (payrollResult.next()) {
                        payrollsPayrollId = payrollResult.getString("payroll_id");
                    }

                    // Fetch advanced_price
                    ResultSet advanceResult = MySql.executeSearch("SELECT advanced_price FROM advanced_payroll WHERE employee_employee_id = '" + employeeId + "'");
                    String advancedPrice = null;
                    if (advanceResult.next()) {
                        advancedPrice = advanceResult.getString("advanced_price");
                    }

                    // Ensure values exist before insertion
                    if (advancedPrice == null) {

                        MySql.executeUpdate("INSERT INTO `payroll_int_hr_details` (`payroll_id`, `date`, `employee_name`, `total_advanced`, `paid_price`, "
                                + "`employee_employee_id`, `employee_payrolls_payroll_id`) VALUES ('" + payRollId + "', '" + currentDate + "', '" + employeeName + "', "
                                + "'" + employeeSalary + "', '0', '" + employeeId + "', '" + payrollsPayrollId + "')");

                        loadtable();

                        JOptionPane.showMessageDialog(this, "Payroll details inserted successfully!");

                    } else {

                        MySql.executeUpdate("INSERT INTO `payroll_int_hr_details` (`payroll_id`, `date`, `employee_name`, `total_advanced`, `paid_price`, "
                                + "`employee_employee_id`, `employee_payrolls_payroll_id`) VALUES ('" + payRollId + "', '" + currentDate + "', '" + employeeName + "', "
                                + "'" + employeeSalary + "', '" + advancedPrice + "', '" + employeeId + "', '" + payrollsPayrollId + "')");
                        loadtable();

                        reset();

                        JOptionPane.showMessageDialog(this, "Payroll details inserted successfully!");

                    }
                }
            } catch (Exception e) {

                e.printStackTrace();

                JOptionPane.showMessageDialog(this, "Error inserting data!", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void employeeIDTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIDTextFieldKeyReleased

        String EmplyeeId = employeeIDTextField.getText();

        try {

            if (EmplyeeId.isEmpty()) {

                employeeNameTextField.setText("");
                employeeIDTextField.setEditable(true);
                employeeNameTextField.setEditable(false);
                return;

            }

            ResultSet rs = MySql.executeSearch("SELECT * FROM `employee` INNER JOIN `employee_payrolls`"
                    + " ON `employee_payrolls`.`employee_employee_id` = `employee`.`employee_id` WHERE `employee_id` = '" + EmplyeeId + "' ");

            if (rs.next()) {

                String fname = rs.getString("first_name");
                String lname = rs.getString("last_name");
                String fullname = fname + " " + lname;
                String employeeSalary = rs.getString("employee_payrolls.payable_salary");

                employeeNameTextField.setText(fullname);

                employeeSalaryFormattedTextField.setText(employeeSalary);

            } else {

                employeeNameTextField.setText("");
                employeeNameTextField.setEditable(false);

            }

        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_employeeIDTextFieldKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.rowAtPoint(evt.getPoint());

        if (row == -1) {
            
            JOptionPane.showMessageDialog(this, "Empty row", "Please select a row", JOptionPane.WARNING_MESSAGE);
        }

        String payID = jTable1.getValueAt(row, 0).toString();
        
        payrollIDTextField.setText(payID);

        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            
            String fullName = jTable1.getValueAt(row, 2).toString();

            int confirm = JOptionPane.showConfirmDialog(this,
                    
                    "Are you sure you want to delete " + fullName + "?",
                    "Delete Confirmation",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                
                try {
                    
                    MySql.executeUpdate("DELETE FROM `payroll_int_hr_details` WHERE `payroll_id` = '" + payID + "'");
                    
                    JOptionPane.showMessageDialog(this, fullName + " deleted successfully", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                    
                    loadtable();
                    
                    reset();
                    
                } catch (Exception e) {
                    
                    e.printStackTrace();
                    
                    JOptionPane.showMessageDialog(this, "Error deleting user", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
            
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void generateButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_generateButtonKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            payrollIDTextField.grabFocus();

        }

    }//GEN-LAST:event_generateButtonKeyPressed

    private void payrollIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payrollIDTextFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            employeeIDTextField.grabFocus();

        }

    }//GEN-LAST:event_payrollIDTextFieldKeyPressed

    private void employeeIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeIDTextFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            employeeNameTextField.grabFocus();

        }

    }//GEN-LAST:event_employeeIDTextFieldKeyPressed

    private void employeeNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeNameTextFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            employeeSalaryFormattedTextField.grabFocus();

        }

    }//GEN-LAST:event_employeeNameTextFieldKeyPressed

    private void employeeSalaryFormattedTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeSalaryFormattedTextFieldKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            addButton.doClick();

        }

    }//GEN-LAST:event_employeeSalaryFormattedTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollIntegrations().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JPanel BackToDashboardPanel;
    private com.k33ptoo.components.KButton addButton;
    private javax.swing.JPanel bodyPanal;
    private javax.swing.JTextField employeeIDTextField;
    private javax.swing.JTextField employeeNameTextField;
    private javax.swing.JFormattedTextField employeeSalaryFormattedTextField;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton generateButton1;
    private javax.swing.JPanel headerPanal;
    private javax.swing.JLabel headingText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton payAdvancedButton;
    private javax.swing.JTextField payrollIDTextField;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    private void reset() {

        payrollIDTextField.setText("");
        generateButton.grabFocus();
        employeeIDTextField.setText("");
        employeeNameTextField.setText("");
        employeeSalaryFormattedTextField.setText("");
        jTable1.clearSelection();

    }

}
