/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finance_department_gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySql;

/**
 *
 * @author GOLDEN FIELD
 */
public class AddCompanyPromotionTypes extends javax.swing.JFrame {

    /**
     * Creates new form AddCompanyPromotionTypes
     */
    public AddCompanyPromotionTypes() {

        initComponents();
        LoadPromotionTable();

    }

    private void LoadPromotionTable() {

        try {

            ResultSet resultSet = MySql.executeSearch("SELECT * FROM `company_promotion_types` ");

            DefaultTableModel defaultTableModel = (DefaultTableModel) PromotionTable.getModel();

            defaultTableModel.setRowCount(0);

            while (resultSet.next()) {

                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("promotiontypes_id"));
                vector.add(resultSet.getString("type_name"));
                vector.add(resultSet.getString("description"));
                vector.add(resultSet.getString("date"));

                defaultTableModel.addRow(vector);

            }

        } catch (Exception e) {

            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        PromotionAddingSectionPanel = new javax.swing.JPanel();
        AddPromotionTypesTextField = new javax.swing.JTextField();
        PromotionTypesDescriptionTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddPromotionButton = new com.k33ptoo.components.KButton();
        BackToDashboardPanel = new javax.swing.JPanel();
        BackToDashboardButton = new javax.swing.JButton();
        PromotionAddingTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PromotionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(153, 153, 153));
        headerPanel.setPreferredSize(new java.awt.Dimension(736, 50));

        jLabel1.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Company Promotion Adding");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        BodyPanel.setLayout(new java.awt.BorderLayout());

        AddPromotionTypesTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AddPromotionTypesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPromotionTypesTextFieldActionPerformed(evt);
            }
        });

        PromotionTypesDescriptionTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Promotion Type");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Promotion Type Description");

        AddPromotionButton.setText("Add");
        AddPromotionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddPromotionButton.setkEndColor(new java.awt.Color(0, 204, 204));
        AddPromotionButton.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        AddPromotionButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddPromotionButton.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        AddPromotionButton.setkPressedColor(new java.awt.Color(0, 102, 153));
        AddPromotionButton.setkSelectedColor(new java.awt.Color(0, 102, 153));
        AddPromotionButton.setkStartColor(new java.awt.Color(0, 102, 153));
        AddPromotionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPromotionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PromotionAddingSectionPanelLayout = new javax.swing.GroupLayout(PromotionAddingSectionPanel);
        PromotionAddingSectionPanel.setLayout(PromotionAddingSectionPanelLayout);
        PromotionAddingSectionPanelLayout.setHorizontalGroup(
            PromotionAddingSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PromotionAddingSectionPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(AddPromotionTypesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(PromotionTypesDescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(AddPromotionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jSeparator1)
        );
        PromotionAddingSectionPanelLayout.setVerticalGroup(
            PromotionAddingSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PromotionAddingSectionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PromotionAddingSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PromotionAddingSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PromotionAddingSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddPromotionTypesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPromotionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PromotionTypesDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BodyPanel.add(PromotionAddingSectionPanel, java.awt.BorderLayout.PAGE_START);

        BackToDashboardPanel.setBackground(new java.awt.Color(153, 153, 153));
        BackToDashboardPanel.setPreferredSize(new java.awt.Dimension(764, 50));

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackToDashboardPanelLayout = new javax.swing.GroupLayout(BackToDashboardPanel);
        BackToDashboardPanel.setLayout(BackToDashboardPanelLayout);
        BackToDashboardPanelLayout.setHorizontalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(1155, Short.MAX_VALUE))
        );
        BackToDashboardPanelLayout.setVerticalGroup(
            BackToDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackToDashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BodyPanel.add(BackToDashboardPanel, java.awt.BorderLayout.PAGE_END);

        PromotionTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PromotionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Promotion Types ID", "Promotion Type", "Promotion Description", "Promotion Adding Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PromotionTable.getTableHeader().setReorderingAllowed(false);
        PromotionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PromotionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PromotionTable);

        javax.swing.GroupLayout PromotionAddingTablePanelLayout = new javax.swing.GroupLayout(PromotionAddingTablePanel);
        PromotionAddingTablePanel.setLayout(PromotionAddingTablePanelLayout);
        PromotionAddingTablePanelLayout.setHorizontalGroup(
            PromotionAddingTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PromotionAddingTablePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        PromotionAddingTablePanelLayout.setVerticalGroup(
            PromotionAddingTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PromotionAddingTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        BodyPanel.add(PromotionAddingTablePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(BodyPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddPromotionTypesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPromotionTypesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPromotionTypesTextFieldActionPerformed

    //BackTodashboardButton

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed

        dispose();

    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        reset();

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void AddPromotionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPromotionButtonActionPerformed

        try {

            String addPromotion = AddPromotionTypesTextField.getText();
            String promotionType = PromotionTypesDescriptionTextField.getText();

            if (addPromotion.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Enter Add Promotion Type", "Warning", JOptionPane.WARNING_MESSAGE);

            } else if (promotionType.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please Enter Promotion Type Description", "Warning", JOptionPane.WARNING_MESSAGE);

            } else {

                LocalDate currentDate = LocalDate.now();
                String formattedDate = currentDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

                MySql.executeUpdate("INSERT INTO `company_promotion_types` (`type_name`,`description`,`date`) VALUES ( '" + addPromotion + "','" + promotionType + "','" + formattedDate + "')");

                LoadPromotionTable();

                reset();

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }//GEN-LAST:event_AddPromotionButtonActionPerformed

    private void PromotionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromotionTableMouseClicked

        // Get the index of the selected row in the table
        int row = PromotionTable.getSelectedRow();

        // Display the data of the selected row in the text fields
        AddPromotionTypesTextField.setText(String.valueOf(PromotionTable.getValueAt(row, 1)));
        PromotionTypesDescriptionTextField.setText(String.valueOf(PromotionTable.getValueAt(row, 2)));

        // Disable the Add button while deleting
        AddPromotionButton.setEnabled(false);

        // Check if the user double-clicked on a row
        if (evt.getClickCount() == 2) {

            String selectedID = String.valueOf(PromotionTable.getValueAt(row, 0));

            // Asking to confirm before the deletion
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Company Promotion Types?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

            //If user confirms the deletion
            if (confirm == JOptionPane.YES_OPTION) {

                try {

                    //Delete from database
                    MySql.executeUpdate("DELETE FROM `company_promotion_types` WHERE  `promotiontypes_id`='" + selectedID + "' ");

                    // Renumber remaining rows
                    MySql.executeUpdate("SET @row_number = 0");
                    MySql.executeUpdate("UPDATE `company_promotion_types`"
                            + "SET  `promotiontypes_id` = (@row_number := @row_number + 1) "
                            + "ORDER BY  `promotiontypes_id`");

                    // Reset AUTO_INCREMENT value
                    MySql.executeUpdate("ALTER TABLE `company_promotion_types` AUTO_INCREMENT = 1");

                    // Reload the jtable table 
                    LoadPromotionTable();
                    reset();

                    //Success message
                    JOptionPane.showMessageDialog(this, "Employee Company Promotion Type Deleted Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {

                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error occurred while deleting the Company Promotion Type", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }


    }//GEN-LAST:event_PromotionTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompanyPromotionTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddPromotionButton;
    private javax.swing.JTextField AddPromotionTypesTextField;
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JPanel BackToDashboardPanel;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel PromotionAddingSectionPanel;
    private javax.swing.JPanel PromotionAddingTablePanel;
    private javax.swing.JTable PromotionTable;
    private javax.swing.JTextField PromotionTypesDescriptionTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables

    private void reset() {

        AddPromotionTypesTextField.setText("");
        PromotionTypesDescriptionTextField.setText("");

        AddPromotionButton.setEnabled(true);
        PromotionTable.clearSelection();

    }

}
